"""added device info for refresh token

Revision ID: 880acc01eaa8
Revises: a7944c6deb50
Create Date: 2026-02-21 18:28:17.089322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '880acc01eaa8'
down_revision: Union[str, Sequence[str], None] = 'a7944c6deb50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('device_info', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'device_info')
    # ### end Alembic commands ###
